### ISSUE TITLE
Wrong order of selected tabs during back press?

### ISSUE THREAD

**Issue by wman1980** [tunjid/Android-Extensions#102] opened 2021-03-11 16:40 UTC
Hi @tunjid,

its me again! :)

If I start you example project and click myself through the tabs in the following order

> Nav, Lists, Comms, Misc, Comms, Lists, Nav (From left to right and back to left)

I would expect that while I am pressing the back button I would go through 

> Lists, Comms, Misc, Comms, Lists, Nav and finally app is moved to background

but instead the order is 

> Lists, Comms, Misc and finally app is moved to background

is that the right behavior?

**Comment by wman1980** [comment] 2021-03-11 16:44
See this example video:

https://user-images.githubusercontent.com/3774028/110822436-59006900-8291-11eb-8cec-0cfbd461ea4f.mov

**Comment by wman1980** [comment] 2021-03-11 16:46
Here is a little example video:

https://user-images.githubusercontent.com/3774028/110822772-b2689800-8291-11eb-8403-d24b18998f19.mov

**Comment by tunjid** [comment] 2021-03-11 18:19
@wman1980 currently that's the intended behavior, I was copying Instagram on this front; each tab is only represented once in the stack for each tab.

Feel free to create an issue to support the use case you want and I'll take a whack at it.

**Comment by wman1980** [comment] 2021-03-12 09:51
Hm ... not shure.

What would be the default/recommended behavior by material design?

Haven't found anything regarding back tab navigation ...

**Comment by tunjid** [comment] 2021-03-15 17:34
@wman1980 the closest I was able to find was this: https://material.io/design/navigation/understanding-navigation.html#reverse-navigation

If one were to follow that strictly, what you expect should be the desired behavior. It does bring up the problem that the stack for the tab history can get arbitrarily large. Not world breakingly so, but its one more thing to consider.

**Comment by wman1980** [comment] 2021-03-18 13:27
Regarding arbitrarily large:
* you could introduce a backStackType enum
* that enum could be set to type "instagram" (default), "endless" or "custom(amount)"
* For type custom you could define a max count of tabs in back history. If that max count is reached you simple delete the first entry within the tabs back history

Hope you get my idea?

**Comment by tunjid** [comment] 2021-03-18 14:33
@wman1980 sure thing, will do.

**Comment by tunjid** [comment] 2021-03-21 13:07
Closing this, will be in the next release.

**Closed by tunjid** 2021-03-21 13:07 UTC
